Checkbox
Perttu-Kangas/ohtu-mini pull request #47
Opened 2022-12-09 14:48 UTC by joonas-a

viitteitä voi valita / poistaa valitut viitteet

2022-12-09 15:06 UTC, DeeCaaD requested changes
Hyvältä vaikuttaa! Ennen poistoa pitää kuitenkin checkata, että kyseinen käyttäjä on viitteiden omistaja.

Eli siis `delete_selected` metodin queryyn lisäys ``WHERE user_id=session_user_id AND id IN ... ``

2022-12-09 15:06 UTC, DeeCaaD commented on src/services/reference.py
> +def delete_selected(ids: list):
Tässä ei tarkasteta onko pyynnön tekijä kyseisten viitteiden omistaja

2022-12-11 09:31 UTC, joonas-a commented on src/services/reference.py
> +def delete_selected(ids: list):
Tämä on nyt korjattu

2022-12-11 12:39 UTC, DeeCaaD approved these changes
Hyvä hyvä

2022-12-11 12:41 UTC, merged